extends: standard
plugins:
  - react
rules:
  array-bracket-spacing:
    - error
    - never
  brace-style:
    - error
    - stroustrup
    - allowSingleLine: true
  comma-dangle:
    - error
    - always-multiline
  indent:
    - error
    - 4
    - SwitchCase: 1
  no-multi-spaces:
    - error
    - exceptions:
        ImportDeclaration: true
        Property: true
        VariableDeclarator: true
  no-multiple-empty-lines:
    - error
    - max: 2
  no-unused-vars:
    - error
    - varsIgnorePattern: "m"
  object-curly-spacing:
    - error
    - always
  operator-linebreak:
    - error
    - before
  react/jsx-uses-react: 2
  react/jsx-uses-vars: 2
  quotes:
    - error
    - single
